### ISSUE TITLE
Issues and suggestions

### ISSUE THREAD

**Issue by Weiyeahh** [ngarcia2024/OIM3690-Project#2]
Good things:
1. Integrated Instagram page! Very easy to click through
2. A gif is added which made the website more interactive
Issues:
Sitemap page needs to be updated 
video wasn't playing and google map insert wasn't working. 
Suggestion on content:
1.Add more images
2.Change the padding of each div to make it more visually pleasing.

**Comment by ngarcia2024** [comment]
Thank you! I will definitely implement these suggestions.
