### ISSUE TITLE
Project Peer Review

### ISSUE THREAD

**Issue by brianacampos** [ngarcia2024/OIM3690-Project#3]
First, I really like how you're making a website for a club that you are a part of on campus. I really like the personal connection because you can even continue using it through the semester!

**2 technical issues/bugs/suggestions**

- Issue #1: I notice that in the events page, you are using in-line css which we are not allowed to use. I suggest using external css. This is the line I am referring to:
https://github.com/ngarcia2024/OIM3690-Project/blob/9497cda2cfecca2ea5829e4d531090b867ce13d6/events.html#L49

- Issue #2: I would also suggest styling the header of the page in order to make it bigger and bring more attention to it, possibly putting it in place of the page title.

**2 suggestions on content**

-Issue #1: I think that on the homepage, the copyright part would look best if put separate. For example, you can make a footer so that it separates it from the content shown, making it more pleasing to the eye.

- Issue #2: I also think that it would be much better if you added pictures. I kinda feel like the website is pure text with very little visuals. Maybe add pictures of past events that you held? or if it's a new club maybe add pictures of Babson, at least for background and visuals.

Overall, I think this is a great page! I hope the best for your club!

**Comment by ngarcia2024** [comment]
Thank you! I will definitely implement these suggestions.
